default: &default
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: store
  username: rails
  password: rails
  pool: 10
  timeout: 5000

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
